import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  background: {
    flex: 1,
    backgroundColor: '#78A2E8',
  },
  keyboardView: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    paddingTop: 4,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  backLabel: {
    fontSize: 18,
    color: '#FFFFFF',
    fontWeight: '700',
  },
  resourcesButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  resourcesLabel: {
    fontSize: 16,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 16,
  },
  avatarContainer: {
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 16,
  },
  videoWrapper: {
    width: 200,
    height: 200,
    borderRadius: 100,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderWidth: 3,
    borderColor: 'rgba(148, 163, 184, 0.3)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 6,
  },
  video: {
    width: '100%',
    height: '100%',
  },
  voiceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 16,
    justifyContent: 'center',
  },
  voiceToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.8)',
  },
  voiceToggleOn: {
    borderColor: '#14B8A6',
    backgroundColor: 'rgba(20, 184, 166, 0.25)',
  },
  voiceLabel: {
    fontSize: 13,
    color: '#1D4ED8',
    fontWeight: '600',
  },
  voiceLabelOn: {
    color: '#0F766E',
  },
  conversationArea: {
    marginBottom: 14,
  },
  messageSpacing: {
    marginBottom: 10,
  },
  messageBubble: {
    borderRadius: 22,
    paddingHorizontal: 18,
    paddingVertical: 14,
    maxWidth: '86%',
  },
  avatarBubble: {
    backgroundColor: '#F7FAFF',
    borderBottomLeftRadius: 8,
    borderTopLeftRadius: 10,
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: 'rgba(102, 134, 187, 0.22)',
    shadowColor: '#1E3A8A',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 2,
  },
  typingBubble: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  typingText: {
    fontStyle: 'italic',
    opacity: 0.85,
  },
  userBubble: {
    backgroundColor: '#2858CC',
    borderBottomRightRadius: 8,
    borderTopRightRadius: 10,
    alignSelf: 'flex-end',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    shadowColor: '#1E3A8A',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 2,
  },
  messageText: {
    fontSize: 15,
    lineHeight: 23,
    ...Platform.select({
      ios: { fontFamily: 'system', fontWeight: '400' },
      android: { fontFamily: 'sans-serif', fontWeight: '400' },
      default: { fontFamily: 'system', fontWeight: '400' },
    }),
  },
  avatarMessageText: {
    color: '#1F2A44',
  },
  userMessageText: {
    color: '#FFFFFF',
  },
  quickPrompts: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  quickPrompt: {
    backgroundColor: '#EEF4FF',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(37, 99, 235, 0.28)',
  },
  quickPromptText: {
    fontSize: 15,
    color: '#1F4FC2',
    fontWeight: '700',
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 10,
    gap: 12,
    backgroundColor: 'transparent',
  },
  inputShell: {
    flex: 1,
    borderRadius: 26,
    backgroundColor: '#F6FAFF',
    borderWidth: 1,
    borderColor: 'rgba(165, 191, 230, 0.9)',
    shadowColor: '#1E3A8A',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 1,
  },
  inputShellFocused: {
    borderColor: '#14B8A6',
    shadowOpacity: 0.16,
  },
  input: {
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 11,
    paddingTop: 11,
    fontSize: 16,
    color: '#21304C',
    maxHeight: 110,
    minHeight: 50,
  },
  inputFocused: {
    color: '#17233A',
  },
  sendButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#14B8A6',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#0F766E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  sendButtonDisabled: {
    backgroundColor: 'rgba(20, 184, 166, 0.45)',
  },
});
