import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  background: {
    flex: 1,
    paddingBottom: 24,
  },
  header: {
    paddingHorizontal: 16,
    paddingTop: 6,
    gap: 10,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    alignSelf: 'flex-start',
  },
  backLabel: {
    fontSize: 17,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  title: {
    fontSize: 34,
    color: '#FFFFFF',
    ...Platform.select({
      ios: { fontWeight: '800' },
      android: { fontFamily: 'sans-serif-medium', fontWeight: '700' },
      default: { fontWeight: '800' },
    }),
  },
  pickerWrap: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 16,
    marginTop: 10,
  },
  pickerButton: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 4,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#D8E8FF',
  },
  pickerButtonSelected: {
    backgroundColor: '#FFFFFF',
  },
  pickerText: {
    color: '#15356F',
    fontWeight: '700',
    fontSize: 12,
  },
  gameWrap: {
    flex: 1,
    marginTop: 16,
    marginHorizontal: 16,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    padding: 20,
    alignItems: 'center',
    gap: 14,
  },
  gameWrapLarge: {
    flex: 1,
    marginTop: 12,
    marginHorizontal: 16,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    padding: 16,
    alignItems: 'center',
  },
  gameScroll: {
    flex: 1,
    width: '100%',
  },
  gameScrollContent: {
    paddingBottom: 32,
    gap: 10,
    alignItems: 'center',
  },
  gameTitle: {
    fontSize: 26,
    color: '#15356F',
    fontWeight: '800',
  },
  gameDescription: {
    textAlign: 'center',
    color: '#35528E',
    fontSize: 15,
    paddingHorizontal: 4,
  },
  orb: {
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: '#7BAEF9',
    shadowColor: '#4A90E2',
    shadowOpacity: 0.5,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
    marginTop: 6,
  },
  breathingStatus: {
    fontSize: 18,
    color: '#1D4ED8',
    fontWeight: '600',
  },
  primaryCta: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#1D4ED8',
    borderRadius: 12,
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  primaryCtaText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  rippleField: {
    flex: 1,
    width: '100%',
    borderRadius: 16,
    backgroundColor: '#D9EFFF',
    minHeight: 320,
    overflow: 'hidden',
  },
  ripple: {
    position: 'absolute',
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#1D4ED8',
  },
  levelSelector: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
    alignSelf: 'flex-start',
  },
  levelChip: {
    minWidth: 42,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 9,
    backgroundColor: '#E8F0FF',
    alignItems: 'center',
  },
  levelChipActive: {
    backgroundColor: '#1D4ED8',
  },
  levelChipText: {
    color: '#1D4ED8',
    fontWeight: '700',
    fontSize: 13,
  },
  levelChipTextActive: {
    color: '#FFFFFF',
  },
  hintToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#E8F0FF',
    borderRadius: 10,
    alignSelf: 'flex-start',
  },
  hintToggleText: {
    color: '#1D4ED8',
    fontSize: 14,
    fontWeight: '600',
  },
  goalPreview: {
    width: '100%',
    backgroundColor: '#F0F9FF',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#C5E1F5',
    gap: 6,
  },
  goalTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#15356F',
  },
  goalText: {
    fontSize: 14,
    color: '#35528E',
  },
  goalTextSimple: {
    fontSize: 15,
    color: '#35528E',
    lineHeight: 24,
  },
  goalTextBridge: {
    fontSize: 14,
    color: '#2E7CA3',
    fontWeight: '600',
    lineHeight: 22,
  },
  goalHint: {
    fontSize: 13,
    color: '#2B6E50',
    fontWeight: '600',
  },
  goalDiagram: {
    width: '100%',
    marginVertical: 8,
  },
  goalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  goalTileWrap: {
    alignItems: 'center',
    gap: 4,
  },
  goalTile: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: '#E8F5DF',
    borderWidth: 2,
    borderColor: '#B8D4B0',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  goalChannelH: {
    width: 28,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#4DB8C4',
  },
  goalArrow: {
    paddingHorizontal: 2,
  },
  goalLabelSpring: {
    fontSize: 11,
    fontWeight: '700',
    color: '#5A9B6E',
  },
  goalLabelGate: {
    fontSize: 11,
    fontWeight: '700',
    color: '#4A8AB8',
  },
  puzzleHeaderRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  puzzleBadge: {
    backgroundColor: '#E6F6EC',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
  },
  puzzleBadgeText: {
    color: '#2B6E50',
    fontSize: 14,
    fontWeight: '700',
  },
  puzzleBadgeMuted: {
    backgroundColor: '#EEF2FB',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
  },
  puzzleBadgeMutedText: {
    color: '#4B5E82',
    fontSize: 13,
    fontWeight: '600',
  },
  secondaryCta: {
    marginLeft: 'auto',
    backgroundColor: '#E8F0FF',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  secondaryCtaText: {
    color: '#1D4ED8',
    fontWeight: '700',
  },
  gardenWorld: {
    width: '100%',
    minHeight: 340,
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#C6E5D9',
    paddingTop: 20,
    backgroundColor: '#DDF3EA',
  },
  gameBoardWrapper: {
    backgroundColor: '#5a9a9a',
    borderColor: '#4a8a8a',
  },
  ambientCloud: {
    position: 'absolute',
    width: 88,
    height: 28,
    borderRadius: 14,
    top: 22,
    left: 22,
    backgroundColor: '#EFFAF4',
    opacity: 0.8,
  },
  ambientCloud2: {
    position: 'absolute',
    width: 62,
    height: 22,
    borderRadius: 12,
    top: 58,
    right: 30,
    backgroundColor: '#F3FBF7',
    opacity: 0.9,
  },
  puzzleGridFlat: {
    paddingHorizontal: 10,
    gap: 8,
    zIndex: 10,
  },
  puzzleRowFlat: {
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
  },
  puzzleTileFlat: {
    borderRadius: 10,
    backgroundColor: '#E5F2E0',
    borderWidth: 2,
    borderColor: '#B8D4B0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tileSurfaceFlat: {
    width: '100%',
    height: '100%',
    borderRadius: 8,
    backgroundColor: '#E8F5DF',
    overflow: 'hidden',
  },
  puzzleTileReachable: {
    borderColor: '#74B7A8',
  },
  channel: {
    position: 'absolute',
    backgroundColor: '#4DB8C4',
  },
  channelN: {
    width: 12,
    height: '45%',
    top: 0,
    left: '50%',
    marginLeft: -6,
  },
  channelE: {
    width: '45%',
    height: 12,
    right: 0,
    top: '50%',
    marginTop: -6,
  },
  channelS: {
    width: 12,
    height: '45%',
    bottom: 0,
    left: '50%',
    marginLeft: -6,
  },
  channelW: {
    width: '45%',
    height: 12,
    left: 0,
    top: '50%',
    marginTop: -6,
  },
  channelCenter: {
    position: 'absolute',
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#3CA8B5',
    top: '50%',
    left: '50%',
    marginTop: -7,
    marginLeft: -7,
  },
  tileObstacleFlat: {
    position: 'absolute',
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#5E6B77',
    top: 6,
    right: 6,
  },
  tileStart: {
    borderColor: '#5CA67A',
  },
  tileGoal: {
    borderColor: '#4A8AB8',
  },
  flatTileLabel: {
    position: 'absolute',
    bottom: 4,
    left: '50%',
    marginLeft: -28,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
    minWidth: 56,
    alignItems: 'center',
    justifyContent: 'center',
  },
  flatTileLabelSpring: {
    backgroundColor: '#1e6e4a',
  },
  flatTileLabelGate: {
    backgroundColor: '#1a4a7a',
  },
  flatTileLabelGateConnected: {
    backgroundColor: '#1A6B4A',
    borderWidth: 2,
    borderColor: '#00d2c8',
  },
  flatTileLabelText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  linkLegend: {
    marginTop: 4,
    alignSelf: 'center',
    backgroundColor: '#E6F5FB',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  linkLegendText: {
    color: '#2E7CA3',
    fontSize: 12,
    fontWeight: '600',
  },
  worldGround: {
    marginTop: 6,
    marginHorizontal: 22,
    borderRadius: 14,
    paddingVertical: 8,
    backgroundColor: '#C9E8CE',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 12,
  },
  puzzleStatus: {
    textAlign: 'center',
    fontSize: 16,
    fontWeight: '600',
    color: '#2B4A6E',
    letterSpacing: 0.4,
    lineHeight: 24,
    paddingHorizontal: 16,
    marginTop: 10,
  },
  puzzleStatusSolved: {
    color: '#1A6B4A',
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  completionActions: {
    marginTop: 16,
    width: '100%',
    alignItems: 'center',
  },
  allCompleteWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#E6F6EC',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#5A9B6E',
  },
  allCompleteText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1A6B4A',
  },
});
